from typing import TypedDict


class PipelineState(TypedDict):
    # --- Input ---
    issue: str                    # Raw feature request / GitHub issue text

    # --- RAG ---
    search_queries: list[str]     # LLM-generated search queries sent to ChromaDB
    rag_context: str              # Concatenated relevant code snippets from the codebase

    # --- Coding Agent ---
    code_draft: str               # Current proposed implementation (full code blocks)
    files_touched: list[str]      # File paths the coding agent created or modified

    # --- QA Reviewer ---
    review_status: str            # "pending" | "pass" | "fail"
    review_feedback: list[str]    # Accumulated list of requested changes across all iterations

    # --- Loop control ---
    iteration_count: int          # How many coding → review loops have completed
    max_iterations: int           # Hard cap to prevent infinite loops (default: 3)

    # --- Output ---
    pr_description: str           # Final markdown PR description generated by PR Publisher
